const data = {
  products: [
    {
      _id: "1",
      name: "Marškinėlis1",
      category: "Marškinėliai",
      image: "/images/d1.jpg",
      price: 30,
      countInStock: 5,
      brand: "DEDAM",
      rating: 4.5,
      numReviews: 10,
      description: "Čia produkto aprašymas",
    },
    {
      _id: "2",
      name: "Marškinėlis2",
      category: "Marškinėliai",
      image: "/images/d2.jpg",
      price: 15,
      countInStock: 8,
      brand: "DEDAM",
      rating: 4,
      numReviews: 15,
      description: "Čia produkto aprašymas",
    },
    {
      _id: "3",
      name: "Marškinėlis3",
      category: "Marškinėliai",
      image: "/images/d3.jpg",
      price: 65,
      countInStock: 9,
      brand: "DEDAM",
      rating: 3.5,
      numReviews: 30,
      description: "Čia produkto aprašymas",
    },
    {
      _id: "4",
      name: "Kepurė1",
      category: "Kepurės",
      image: "/images/d4.jpg",
      price: 75,
      countInStock: 8,
      brand: "DEDAM",
      rating: 1,
      numReviews: 1,
      description: "Čia produkto aprašymas",
    },
    {
      _id: "5",
      name: "Marškinėlis5",
      category: "Marškinėliai",
      image: "/images/d5.jpg",
      price: 13,
      countInStock: 0,
      brand: "DEDAM",
      rating: 5,
      numReviews: 100,
      description: "Čia produkto aprašymas",
    },
    {
      _id: "6",
      name: "Kepurė2",
      category: "Kepurės",
      image: "/images/d6.jpg",
      price: 300,
      countInStock: 50,
      brand: "DEDAM",
      rating: 2.2,
      numReviews: 11,
      description: "Čia produkto aprašymas",
    },
  ],
};
export default data;
